import 'jsdom-global/register';
import chai, { expect } from 'chai';

import reposSearchStar from '../src/scripts/components/reposSearchStar';

describe('Repository Search Star', () => {
	describe('some tests', () => {
		it('should reposSearchStar', () => {
			expect(reposSearchStar).to.exist;
		});
		it('should reposSearchStar is a function', () => {
			expect(reposSearchStar).to.be.a('function');
		});
	});

	const markup = `
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>vibration-api</h3>
				<p>null</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>css-padawan</h3>
				<p>CSS Padawan</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>css-components</h3>
				<p>CSS COMPONENTS</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>battery-status-api</h3>
				<p>null</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>CSS-Reference</h3>
				<p>null</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>ambient-light-api</h3>
				<p>Ambient light events are a useful way to make a web page aware of any change in light intensity</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>sku-color</h3>
				<p>Ele cria de forma rápida um CSS com todas as cores de sku da loja</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>css-quiz</h3>
				<p>CSS Quiz</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>desafio-daily-css-images</h3>
				<p>Challenge Daily CSS Images</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>
		<li class="hot__desktop-4">
			<div class="repos-per-star-item">
				<h3>simple-grid-css</h3>
				<p>Simple Grid CSS</p>
				<i><svg class="icon-account_balance"><use xlink:href="#icon-read-more" xmlns:xlink="http://www.w3.org/1999/xlink"></use></svg></i>
			</div>
		</li>`;

	const data = [
		{
			"id": 95467615,
			"name": "vibration-api",
			"full_name": "hjdesigner/vibration-api",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/vibration-api",
			"description": null,
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/vibration-api",
			"forks_url": "https://api.github.com/repos/hjdesigner/vibration-api/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/vibration-api/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/vibration-api/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/vibration-api/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/vibration-api/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/vibration-api/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/vibration-api/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/vibration-api/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/vibration-api/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/vibration-api/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/vibration-api/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/vibration-api/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/vibration-api/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/vibration-api/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/vibration-api/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/vibration-api/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/vibration-api/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/vibration-api/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/vibration-api/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/vibration-api/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/vibration-api/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/vibration-api/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/vibration-api/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/vibration-api/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/vibration-api/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/vibration-api/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/vibration-api/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/vibration-api/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/vibration-api/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/vibration-api/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/vibration-api/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/vibration-api/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/vibration-api/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/vibration-api/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/vibration-api/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/vibration-api/deployments",
			"created_at": "2017-06-26T16:39:21Z",
			"updated_at": "2017-12-12T12:00:47Z",
			"pushed_at": "2017-12-12T17:37:34Z",
			"git_url": "git://github.com/hjdesigner/vibration-api.git",
			"ssh_url": "git@github.com:hjdesigner/vibration-api.git",
			"clone_url": "https://github.com/hjdesigner/vibration-api.git",
			"svn_url": "https://github.com/hjdesigner/vibration-api",
			"homepage": "http://henriquemelanda.com.br/vibration-api/",
			"size": 191,
			"stargazers_count": 23,
			"watchers_count": 23,
			"language": "HTML",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 6,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": {
				"key": "mit",
				"name": "MIT License",
				"spdx_id": "MIT",
				"url": "https://api.github.com/licenses/mit"
			},
			"forks": 6,
			"open_issues": 0,
			"watchers": 23,
			"default_branch": "master"
		},
		{
			"id": 90907526,
			"name": "css-padawan",
			"full_name": "hjdesigner/css-padawan",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/css-padawan",
			"description": "CSS Padawan",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/css-padawan",
			"forks_url": "https://api.github.com/repos/hjdesigner/css-padawan/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/css-padawan/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/css-padawan/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/css-padawan/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/css-padawan/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/css-padawan/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/css-padawan/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/css-padawan/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/css-padawan/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/css-padawan/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/css-padawan/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/css-padawan/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/css-padawan/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/css-padawan/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/css-padawan/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/css-padawan/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/css-padawan/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/css-padawan/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/css-padawan/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/css-padawan/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/css-padawan/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/css-padawan/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/css-padawan/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/css-padawan/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/css-padawan/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/css-padawan/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/css-padawan/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/css-padawan/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/css-padawan/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/css-padawan/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/css-padawan/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/css-padawan/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/css-padawan/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/css-padawan/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/css-padawan/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/css-padawan/deployments",
			"created_at": "2017-05-10T20:54:51Z",
			"updated_at": "2017-08-03T23:53:42Z",
			"pushed_at": "2017-05-24T03:22:33Z",
			"git_url": "git://github.com/hjdesigner/css-padawan.git",
			"ssh_url": "git@github.com:hjdesigner/css-padawan.git",
			"clone_url": "https://github.com/hjdesigner/css-padawan.git",
			"svn_url": "https://github.com/hjdesigner/css-padawan",
			"homepage": "http://henriquemelanda.com.br/css-padawan",
			"size": 974,
			"stargazers_count": 16,
			"watchers_count": 16,
			"language": "CSS",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 1,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": {
				"key": "mit",
				"name": "MIT License",
				"spdx_id": "MIT",
				"url": "https://api.github.com/licenses/mit"
			},
			"forks": 1,
			"open_issues": 0,
			"watchers": 16,
			"default_branch": "master"
		},
		{
			"id": 65954471,
			"name": "css-components",
			"full_name": "hjdesigner/css-components",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/css-components",
			"description": "CSS COMPONENTS",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/css-components",
			"forks_url": "https://api.github.com/repos/hjdesigner/css-components/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/css-components/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/css-components/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/css-components/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/css-components/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/css-components/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/css-components/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/css-components/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/css-components/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/css-components/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/css-components/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/css-components/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/css-components/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/css-components/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/css-components/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/css-components/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/css-components/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/css-components/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/css-components/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/css-components/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/css-components/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/css-components/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/css-components/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/css-components/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/css-components/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/css-components/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/css-components/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/css-components/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/css-components/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/css-components/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/css-components/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/css-components/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/css-components/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/css-components/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/css-components/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/css-components/deployments",
			"created_at": "2016-08-18T01:25:38Z",
			"updated_at": "2017-02-10T12:25:10Z",
			"pushed_at": "2017-02-25T22:01:36Z",
			"git_url": "git://github.com/hjdesigner/css-components.git",
			"ssh_url": "git@github.com:hjdesigner/css-components.git",
			"clone_url": "https://github.com/hjdesigner/css-components.git",
			"svn_url": "https://github.com/hjdesigner/css-components",
			"homepage": "http://henriquemelanda.com.br/css-components/",
			"size": 1016,
			"stargazers_count": 11,
			"watchers_count": 11,
			"language": "HTML",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 1,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": null,
			"forks": 1,
			"open_issues": 0,
			"watchers": 11,
			"default_branch": "master"
		},
		{
			"id": 95693494,
			"name": "battery-status-api",
			"full_name": "hjdesigner/battery-status-api",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/battery-status-api",
			"description": null,
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/battery-status-api",
			"forks_url": "https://api.github.com/repos/hjdesigner/battery-status-api/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/battery-status-api/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/battery-status-api/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/battery-status-api/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/battery-status-api/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/battery-status-api/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/battery-status-api/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/battery-status-api/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/battery-status-api/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/battery-status-api/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/battery-status-api/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/battery-status-api/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/battery-status-api/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/battery-status-api/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/battery-status-api/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/battery-status-api/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/battery-status-api/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/battery-status-api/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/battery-status-api/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/battery-status-api/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/battery-status-api/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/battery-status-api/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/battery-status-api/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/battery-status-api/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/battery-status-api/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/battery-status-api/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/battery-status-api/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/battery-status-api/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/battery-status-api/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/battery-status-api/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/battery-status-api/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/battery-status-api/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/battery-status-api/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/battery-status-api/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/battery-status-api/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/battery-status-api/deployments",
			"created_at": "2017-06-28T17:14:59Z",
			"updated_at": "2017-06-30T02:28:39Z",
			"pushed_at": "2017-06-29T22:38:07Z",
			"git_url": "git://github.com/hjdesigner/battery-status-api.git",
			"ssh_url": "git@github.com:hjdesigner/battery-status-api.git",
			"clone_url": "https://github.com/hjdesigner/battery-status-api.git",
			"svn_url": "https://github.com/hjdesigner/battery-status-api",
			"homepage": null,
			"size": 125,
			"stargazers_count": 5,
			"watchers_count": 5,
			"language": "HTML",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 1,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": {
				"key": "mit",
				"name": "MIT License",
				"spdx_id": "MIT",
				"url": "https://api.github.com/licenses/mit"
			},
			"forks": 1,
			"open_issues": 0,
			"watchers": 5,
			"default_branch": "master"
		},
		{
			"id": 39413544,
			"name": "CSS-Reference",
			"full_name": "hjdesigner/CSS-Reference",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/CSS-Reference",
			"description": null,
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/CSS-Reference",
			"forks_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/CSS-Reference/deployments",
			"created_at": "2015-07-20T23:31:17Z",
			"updated_at": "2017-03-19T15:23:40Z",
			"pushed_at": "2017-06-13T18:28:28Z",
			"git_url": "git://github.com/hjdesigner/CSS-Reference.git",
			"ssh_url": "git@github.com:hjdesigner/CSS-Reference.git",
			"clone_url": "https://github.com/hjdesigner/CSS-Reference.git",
			"svn_url": "https://github.com/hjdesigner/CSS-Reference",
			"homepage": null,
			"size": 40,
			"stargazers_count": 3,
			"watchers_count": 3,
			"language": "CSS",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": null,
			"forks": 0,
			"open_issues": 0,
			"watchers": 3,
			"default_branch": "master"
		},
		{
			"id": 98181160,
			"name": "ambient-light-api",
			"full_name": "hjdesigner/ambient-light-api",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/ambient-light-api",
			"description": "Ambient light events are a useful way to make a web page aware of any change in light intensity",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/ambient-light-api",
			"forks_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/ambient-light-api/deployments",
			"created_at": "2017-07-24T10:57:39Z",
			"updated_at": "2018-01-25T19:18:55Z",
			"pushed_at": "2017-07-24T20:16:59Z",
			"git_url": "git://github.com/hjdesigner/ambient-light-api.git",
			"ssh_url": "git@github.com:hjdesigner/ambient-light-api.git",
			"clone_url": "https://github.com/hjdesigner/ambient-light-api.git",
			"svn_url": "https://github.com/hjdesigner/ambient-light-api",
			"homepage": "",
			"size": 7,
			"stargazers_count": 2,
			"watchers_count": 2,
			"language": "CSS",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 1,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": {
				"key": "mit",
				"name": "MIT License",
				"spdx_id": "MIT",
				"url": "https://api.github.com/licenses/mit"
			},
			"forks": 1,
			"open_issues": 0,
			"watchers": 2,
			"default_branch": "master"
		},
		{
			"id": 99624018,
			"name": "sku-color",
			"full_name": "hjdesigner/sku-color",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/sku-color",
			"description": "Ele cria de forma rápida um CSS com todas as cores de sku da loja",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/sku-color",
			"forks_url": "https://api.github.com/repos/hjdesigner/sku-color/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/sku-color/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/sku-color/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/sku-color/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/sku-color/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/sku-color/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/sku-color/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/sku-color/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/sku-color/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/sku-color/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/sku-color/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/sku-color/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/sku-color/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/sku-color/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/sku-color/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/sku-color/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/sku-color/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/sku-color/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/sku-color/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/sku-color/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/sku-color/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/sku-color/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/sku-color/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/sku-color/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/sku-color/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/sku-color/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/sku-color/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/sku-color/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/sku-color/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/sku-color/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/sku-color/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/sku-color/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/sku-color/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/sku-color/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/sku-color/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/sku-color/deployments",
			"created_at": "2017-08-07T21:57:16Z",
			"updated_at": "2017-08-22T01:26:51Z",
			"pushed_at": "2017-08-23T14:19:28Z",
			"git_url": "git://github.com/hjdesigner/sku-color.git",
			"ssh_url": "git@github.com:hjdesigner/sku-color.git",
			"clone_url": "https://github.com/hjdesigner/sku-color.git",
			"svn_url": "https://github.com/hjdesigner/sku-color",
			"homepage": "http://henriquemelanda.com.br/sku-color/",
			"size": 675,
			"stargazers_count": 2,
			"watchers_count": 2,
			"language": "CSS",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": null,
			"forks": 0,
			"open_issues": 0,
			"watchers": 2,
			"default_branch": "master"
		},
		{
			"id": 114686913,
			"name": "css-quiz",
			"full_name": "hjdesigner/css-quiz",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/css-quiz",
			"description": "CSS Quiz",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/css-quiz",
			"forks_url": "https://api.github.com/repos/hjdesigner/css-quiz/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/css-quiz/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/css-quiz/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/css-quiz/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/css-quiz/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/css-quiz/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/css-quiz/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/css-quiz/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/css-quiz/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/css-quiz/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/css-quiz/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/css-quiz/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/css-quiz/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/css-quiz/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/css-quiz/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/css-quiz/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/css-quiz/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/css-quiz/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/css-quiz/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/css-quiz/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/css-quiz/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/css-quiz/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/css-quiz/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/css-quiz/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/css-quiz/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/css-quiz/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/css-quiz/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/css-quiz/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/css-quiz/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/css-quiz/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/css-quiz/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/css-quiz/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/css-quiz/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/css-quiz/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/css-quiz/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/css-quiz/deployments",
			"created_at": "2017-12-18T20:56:49Z",
			"updated_at": "2017-12-22T21:18:25Z",
			"pushed_at": "2018-01-01T02:28:17Z",
			"git_url": "git://github.com/hjdesigner/css-quiz.git",
			"ssh_url": "git@github.com:hjdesigner/css-quiz.git",
			"clone_url": "https://github.com/hjdesigner/css-quiz.git",
			"svn_url": "https://github.com/hjdesigner/css-quiz",
			"homepage": null,
			"size": 65,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "JavaScript",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": {
				"key": "mit",
				"name": "MIT License",
				"spdx_id": "MIT",
				"url": "https://api.github.com/licenses/mit"
			},
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master"
		},
		{
			"id": 80833416,
			"name": "desafio-daily-css-images",
			"full_name": "hjdesigner/desafio-daily-css-images",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/desafio-daily-css-images",
			"description": "Challenge Daily CSS Images",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images",
			"forks_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/desafio-daily-css-images/deployments",
			"created_at": "2017-02-03T13:54:44Z",
			"updated_at": "2017-10-25T02:32:56Z",
			"pushed_at": "2017-03-23T02:33:02Z",
			"git_url": "git://github.com/hjdesigner/desafio-daily-css-images.git",
			"ssh_url": "git@github.com:hjdesigner/desafio-daily-css-images.git",
			"clone_url": "https://github.com/hjdesigner/desafio-daily-css-images.git",
			"svn_url": "https://github.com/hjdesigner/desafio-daily-css-images",
			"homepage": "http://henriquemelanda.com.br/galeria-daily-css-images/",
			"size": 100,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "CSS",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": null,
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master"
		},
		{
			"id": 89977625,
			"name": "simple-grid-css",
			"full_name": "hjdesigner/simple-grid-css",
			"owner": {
				"login": "hjdesigner",
				"id": 2280313,
				"avatar_url": "https://avatars3.githubusercontent.com/u/2280313?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/hjdesigner",
				"html_url": "https://github.com/hjdesigner",
				"followers_url": "https://api.github.com/users/hjdesigner/followers",
				"following_url": "https://api.github.com/users/hjdesigner/following{/other_user}",
				"gists_url": "https://api.github.com/users/hjdesigner/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/hjdesigner/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/hjdesigner/subscriptions",
				"organizations_url": "https://api.github.com/users/hjdesigner/orgs",
				"repos_url": "https://api.github.com/users/hjdesigner/repos",
				"events_url": "https://api.github.com/users/hjdesigner/events{/privacy}",
				"received_events_url": "https://api.github.com/users/hjdesigner/received_events",
				"type": "User",
				"site_admin": false
			},
			"private": false,
			"html_url": "https://github.com/hjdesigner/simple-grid-css",
			"description": "Simple Grid CSS",
			"fork": false,
			"url": "https://api.github.com/repos/hjdesigner/simple-grid-css",
			"forks_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/forks",
			"keys_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/keys{/key_id}",
			"collaborators_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/collaborators{/collaborator}",
			"teams_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/teams",
			"hooks_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/hooks",
			"issue_events_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/issues/events{/number}",
			"events_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/events",
			"assignees_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/assignees{/user}",
			"branches_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/branches{/branch}",
			"tags_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/tags",
			"blobs_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/git/blobs{/sha}",
			"git_tags_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/git/tags{/sha}",
			"git_refs_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/git/refs{/sha}",
			"trees_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/git/trees{/sha}",
			"statuses_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/statuses/{sha}",
			"languages_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/languages",
			"stargazers_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/stargazers",
			"contributors_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/contributors",
			"subscribers_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/subscribers",
			"subscription_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/subscription",
			"commits_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/commits{/sha}",
			"git_commits_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/git/commits{/sha}",
			"comments_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/comments{/number}",
			"issue_comment_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/issues/comments{/number}",
			"contents_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/contents/{+path}",
			"compare_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/compare/{base}...{head}",
			"merges_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/merges",
			"archive_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/{archive_format}{/ref}",
			"downloads_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/downloads",
			"issues_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/issues{/number}",
			"pulls_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/pulls{/number}",
			"milestones_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/milestones{/number}",
			"notifications_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/notifications{?since,all,participating}",
			"labels_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/labels{/name}",
			"releases_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/releases{/id}",
			"deployments_url": "https://api.github.com/repos/hjdesigner/simple-grid-css/deployments",
			"created_at": "2017-05-02T01:16:44Z",
			"updated_at": "2017-09-11T14:31:35Z",
			"pushed_at": "2017-05-03T13:50:32Z",
			"git_url": "git://github.com/hjdesigner/simple-grid-css.git",
			"ssh_url": "git@github.com:hjdesigner/simple-grid-css.git",
			"clone_url": "https://github.com/hjdesigner/simple-grid-css.git",
			"svn_url": "https://github.com/hjdesigner/simple-grid-css",
			"homepage": null,
			"size": 48,
			"stargazers_count": 1,
			"watchers_count": 1,
			"language": "HTML",
			"has_issues": true,
			"has_projects": true,
			"has_downloads": true,
			"has_wiki": true,
			"has_pages": false,
			"forks_count": 0,
			"mirror_url": null,
			"archived": false,
			"open_issues_count": 0,
			"license": {
				"key": "mit",
				"name": "MIT License",
				"spdx_id": "MIT",
				"url": "https://api.github.com/licenses/mit"
			},
			"forks": 0,
			"open_issues": 0,
			"watchers": 1,
			"default_branch": "master"
		},
	];

	it('should create and append when more than 1 repository', () => {
		const element = document.createElement('div');
		reposSearchStar(data, element);
		expect(element.innerHTML).to.be.eql(markup);
	});

	it('should return the data', () => {
		const element2 = document.createElement('div');
		expect(reposSearchStar(data, element2)).to.be.eql(data);
	});

});
